### ISSUE TITLE
failed in building linux kernel 6.10.9 on kali 

### ISSUE THREAD

**Issue by Yacine-Naoui** [xtrx-sdr/xtrx_linux_pcie_drv#21]
here is the issue : **Setting up xtrx-dkms (0.0.1+git20190320.5ae3a3e-4~kali1) ...
Removing old xtrx-0.0.1+git20190320.5ae3a3e-4~kali1 DKMS files...
Module xtrx-0.0.1+git20190320.5ae3a3e-4~kali1 for kernel 5.15.44-Re4son-v8l+ (aarch64).
Before uninstall, this module version was ACTIVE on this kernel.

xtrx.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.15.44-Re4son-v8l+/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.
depmod...
Deleting module xtrx-0.0.1+git20190320.5ae3a3e-4~kali1 completely from the DKMS tree.
Loading new xtrx-0.0.1+git20190320.5ae3a3e-4~kali1 DKMS files...
Building for 5.15.44-Re4son-v8l+ 6.10.9-arm64
Building initial module for 5.15.44-Re4son-v8l+
Done.

xtrx.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.44-Re4son-v8l+/updates/dkms/
depmod...
Building initial module for 6.10.9-arm64
Error! Bad return status for module build on kernel: 6.10.9-arm64 (aarch64)
Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/make.log for more information.
dpkg: error processing package xtrx-dkms (--configure):
 installed xtrx-dkms package post-installation script subprocess returned error exit status 10
Setting up linux-image-6.10.9-arm64 (6.10.9-1kali1) ...
/etc/kernel/postinst.d/dkms:
dkms: running auto installation service for kernel 6.10.9-arm64.
Sign command: /lib/modules/6.10.9-arm64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
Building module(s)....(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=6.10.9-arm64 -C /lib/modules/6.10.9-arm64/build M=/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build
Error! Bad return status for module build on kernel: 6.10.9-arm64 (aarch64)
Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/make.log for more information.
dkms autoinstall on 6.10.9-arm64/aarch64 failed for xtrx(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.10.9-arm64 failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.10.9-arm64 (--configure):
 installed linux-image-6.10.9-arm64 package post-installation script subprocess returned error exit status 11
dpkg: dependency problems prevent configuration of linux-headers-6.10.9-arm64:
 linux-headers-6.10.9-arm64 depends on linux-image-6.10.9-arm64 (= 6.10.9-1kali1) | linux-image-6.10.9-arm64-unsigned (= 6.10.9-1kali1); however:
  Package linux-image-6.10.9-arm64 is not configured yet.
  Package linux-image-6.10.9-arm64-unsigned is not installed.

dpkg: error processing package linux-headers-6.10.9-arm64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of linux-headers-arm64:
 linux-headers-arm64 depends on linux-headers-6.10.9-arm64 (= 6.10.9-1kali1); however:
  Package linux-headers-6.10.9-arm64 is not configured yet.

dpkg: error processing package linux-headers-arm64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of linux-image-arm64:
 linux-image-arm64 depends on linux-image-6.10.9-arm64 (= 6.10.9-1kali1); however:
  Package linux-image-6.10.9-arm64 is not configured yet.

dpkg: error processing package linux-image-arm64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 xtrx-dkms
 linux-image-6.10.9-arm64
 linux-headers-6.10.9-arm64
 linux-headers-arm64
 linux-image-arm64
E: Sub-process /usr/bin/dpkg returned an error code (1)     
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/make.log:
make: Entering directory '/usr/src/linux-headers-6.10.9-arm64'
  CC [M]  /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.o
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:547:27: error: initialization of ?void (*)(struct uart_port *, struct ktermios *, const struct ktermios *)? from incompatible pointer type ?void (*)(struct uart_port *, struct ktermios *, struct ktermios *)? [-Werror=incompatible-pointer-types]
  547 |         .set_termios    = xtrx_uart_set_termios,
      |                           ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:547:27: note: (near initialization for ?xtrx_uart_ops.set_termios?)
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c: In function ?xtrx_allocdma?:
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:653:33: error: implicit declaration of function ?pci_alloc_consistent? [-Werror=implicit-function-declaration]
  653 |                 pbufs[i].virt = pci_alloc_consistent(d->pdev, buflen, &pbufs[i].phys);
      |                                 ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:653:31: warning: assignment to ?void *? from ?int? makes pointer from integer without a cast [-Wint-conversion]
  653 |                 pbufs[i].virt = pci_alloc_consistent(d->pdev, buflen, &pbufs[i].phys);
      |                               ^
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:657:33: error: implicit declaration of function ?pci_free_consistent? [-Werror=implicit-function-declaration]
  657 |                                 pci_free_consistent(d->pdev, buflen, pbufs[i].virt, pbufs[i].phys);
      |                                 ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c: In function ?xtrxfd_mmap?:
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1083:31: error: assignment of read-only member ?vm_flags?
 1083 |                 vma->vm_flags |= VM_LOCKED;
      |                               ^~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1098:31: error: assignment of read-only member ?vm_flags?
 1098 |                 vma->vm_flags |= VM_IO;
      |                               ^~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1123:31: error: assignment of read-only member ?vm_flags?
 1123 |                 vma->vm_flags |= VM_LOCKED;
      |                               ^~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c: In function ?xtrx_probe?:
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1194:13: error: implicit declaration of function ?pci_set_consistent_dma_mask? [-Werror=implicit-function-declaration]
 1194 |         if (pci_set_consistent_dma_mask(pdev, DMA_BIT_MASK(32))) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/alternative.h:9,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/lse.h:14,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/cmpxchg.h:14,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/atomic.h:16,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/atomic.h:7,
                 from /usr/src/linux-headers-6.10.9-common/include/asm-generic/bitops/atomic.h:5,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/bitops.h:25,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/bitops.h:63,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/cache.h:40,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/cache.h:6,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/time.h:5,
                 from /usr/src/linux-headers-6.10.9-common/arch/arm64/include/asm/stat.h:12,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/stat.h:6,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/module.h:13,
                 from /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:22:
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c: In function ?xtrx_init?:
/usr/src/linux-headers-6.10.9-common/include/linux/init.h:180:22: error: passing argument 1 of ?class_create? from incompatible pointer type [-Werror=incompatible-pointer-types]
  180 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1527:35: note: in expansion of macro ?THIS_MODULE?
 1527 |         xtrx_class = class_create(THIS_MODULE, CLASS_NAME);
      |                                   ^~~~~~~~~~~
In file included from /usr/src/linux-headers-6.10.9-common/include/linux/device.h:31,
                 from /usr/src/linux-headers-6.10.9-common/include/linux/pci.h:37,
                 from /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:25:
/usr/src/linux-headers-6.10.9-common/include/linux/device/class.h:228:54: note: expected ?const char *? but argument is of type ?struct module *?
  228 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.c:1527:22: error: too many arguments to function ?class_create?
 1527 |         xtrx_class = class_create(THIS_MODULE, CLASS_NAME);
      |                      ^~~~~~~~~~~~
/usr/src/linux-headers-6.10.9-common/include/linux/device/class.h:228:29: note: declared here
  228 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.10.9-common/scripts/Makefile.build:249: /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build/xtrx.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.10.9-common/Makefile:1959: /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-4~kali1/build] Error 2
make: *** [/usr/src/linux-headers-6.10.9-common/Makefile:252: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.10.9-arm64'**

**Comment by geerlingguy** [comment]
I'm getting the same thing on Pi OS Bookworm:

```
pi@pi4-sdr:~ $ sudo apt install gqrx-sdr
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gqrx-sdr is already the newest version (2.15.9-1+b2).
0 upgraded, 0 newly installed, 0 to remove and 110 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up xtrx-dkms (0.0.1+git20190320.5ae3a3e-3.2) ...
Removing old xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.
Loading new xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
Building for 6.6.51+rpt-rpi-v8
Building initial module for 6.6.51+rpt-rpi-v8
Error! Bad return status for module build on kernel: 6.6.51+rpt-rpi-v8 (aarch64)
Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/make.log for more information.
dpkg: error processing package xtrx-dkms (--configure):
 installed xtrx-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 xtrx-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Looking inside the log file:

```
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/xtrx.c: In function ‘xtrx_init’:
/usr/src/linux-headers-6.6.51+rpt-common-rpi/include/linux/export.h:29:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   29 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/xtrx.c:1523:35: note: in expansion of macro ‘THIS_MODULE’
 1523 |         xtrx_class = class_create(THIS_MODULE, CLASS_NAME);
      |                                   ^~~~~~~~~~~
In file included from /usr/src/linux-headers-6.6.51+rpt-common-rpi/include/linux/device.h:31,
                 from /usr/src/linux-headers-6.6.51+rpt-common-rpi/include/linux/pci.h:37,
                 from /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/xtrx.c:25:
/usr/src/linux-headers-6.6.51+rpt-common-rpi/include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  230 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/xtrx.c:1523:22: error: too many arguments to function ‘class_create’
 1523 |         xtrx_class = class_create(THIS_MODULE, CLASS_NAME);
      |                      ^~~~~~~~~~~~
/usr/src/linux-headers-6.6.51+rpt-common-rpi/include/linux/device/class.h:230:29: note: declared here
  230 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
```

Looks like this is fixed in https://github.com/myriadrf/xtrx_linux_pcie_drv/commit/d218d3e8be3f723000bdfff6b6235a85f7b10e42 — but that is not in the Debian Bookworm package version.

**Comment by 9600** [comment]
>Looks like this is fixed in https://github.com/myriadrf/xtrx_linux_pcie_drv/commit/d218d3e8be3f723000bdfff6b6235a85f7b10e42 — but that is not in the Debian Bookworm package version.

Right, so the version they distribute will be fairly old.

Out of curiosity which version of XTRX hardware do you have? This old driver for the Fairwaves XTRX is not really maintained and all development is going into the LimeSDR XTRX and Lime Suite NG driver stack. If you have a Fairwaves XTRX Rev. 5 it could be flashed with the FPGA gateware used with LimeSDR XTRX, hence making it compatible with Lime Suite NG.

**Comment by geerlingguy** [comment]
@9600 - I'm actually testing a CaribouLite, and as part of its installation, it seems like it is installing xtrx? Not even sure why. See: https://github.com/cariboulabs/cariboulite/pull/176

**Comment by 9600** [comment]
@geerlingguy Not sure either, doesn't seem to make sense. BTW, just sent you an e-mail.

**Comment by jslatten** [comment]
Is there any solution to get the old fairwaves xtrx driver updated for newer kernels and gcc? I hate the fact that I have good hardware that I'm unable to use. The newer limesdr XTRX is way more expensive and it hurts even more that I'll have to throw away several hundred dollars on the original XTRX that doesn't work then turn around and spend 500+ more. I tried to take a stab at updating the code, however I've realized it is so far beyond my skill set and abilities that it's a bit ridiculous I even tried.

**Comment by 9600** [comment]
@jslatten I'm afraid that we, Lime Microsystems, do not intend to maintain this beyond merging PRs. We have no experience with the legacy Fairwaves codebase. As a goodwill gesture we have ported our FPGA gateware to the Fairwaves XTRX Rev5, which we were able to do because it uses the same FPGA as LimeSDR XTRX. Hence this means that owners of Fairwaves XTRX Rev5 boards can then use Lime Suite NG and its kernel driver, which are actively maintained. However, it would be a lot of extra work to port the gateware to older boards which use a smaller FPGA, or to pick up maintenance for this legacy driver stack.

**Comment by jslatten** [comment]
Thanks for the response @9600. No worries...I wasn't expecting Lime Microsystems to support...I was really just hoping that someone with more low level driver and kernel experience could point in the right direction on how to resolve some of the compile errors. I did some digging and discovered a kind soul (Weston Reed) who updated the driver to support Linux 6.10.x. It can be found here for anyone who may also need it: https://github.com/WestonReed/xtrx_linux_pcie_drv

**Comment by ghost** [comment]
This also fails for kernel 6.14.0-36-generic. During a package update. 
Thanks for the info.
